### ISSUE TITLE
Composer conflicts with guzzlehttp/guzzle 7

### ISSUE THREAD

**Issue by rickyheijnen** [onetoweb/parcelpro#1]
The composer require of guzzlehttp is limited to version [6.5.0, ..., 6.5.5]. Please update this so it is compatible with httpguzzle 7

**Comment by JJSchaart** [comment]
@loki84nl Can you resolve this issue?

**Comment by loki84nl** [comment]
updated, v1.0.4 compatible with httpguzzle 7
